myFlowerExperiment | ERROR flwr 2025-05-16 01:57:41,046 | app.py:152 | ClientApp raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/E2FL/lib/python3.10/site-packages/flwr/client/clientapp/app.py", line 137, in run_clientapp
    reply_message = client_app(message=message, context=context)
  File "/home/ubuntu/anaconda3/envs/E2FL/lib/python3.10/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
  File "/home/ubuntu/anaconda3/envs/E2FL/lib/python3.10/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/ubuntu/anaconda3/envs/E2FL/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/ubuntu/.flwr/apps/wwjang.e2fl.1.0.0.7ce4b6d3/e2fl/client_app.py", line 337, in client_fn
    return FlowerClient(net, trainloader, valloader, local_epochs).to_client()
  File "/home/ubuntu/.flwr/apps/wwjang.e2fl.1.0.0.7ce4b6d3/e2fl/client_app.py", line 68, in __init__
    self.fl_csv_fname = f"fl_{datetime.now().strftime('%Y%m%d')}_{self.device_name}_{self.get_last_octet_from_ip()}.csv"
TypeError: FlowerClient.get_last_octet_from_ip() takes 0 positional arguments but 1 was given
myFlowerExperiment | INFO flwr 2025-05-16 01:57:41,055 | app.py:222 | [flwr-clientapp] Push `ClientAppOutputs` for token 8096936919123695200
