INFO:test:['[2025-05-26 03:10:57.710564] Client Start!']
INFO:test:Using network interface: eth0
INFO:test:[2025-05-26 03:10:57.711263] Starting power monitoring...
ERROR:flwr:ClientApp raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/clientapp/app.py", line 136, in run_clientapp
    reply_message = client_app(message=message, context=context)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/root/.flwr/apps/wwjang.e2fl.1.0.0.464c9a8c/e2fl/client_app.py", line 337, in client_fn
    return FlowerClient(net, trainloader, valloader, local_epochs).to_client()
  File "/root/.flwr/apps/wwjang.e2fl.1.0.0.464c9a8c/e2fl/client_app.py", line 68, in __init__
    self.fl_csv_fname = f"fl_{datetime.now().strftime('%Y%m%d')}_{self.device_name}_{self.get_last_octet_from_ip()}.csv"
TypeError: FlowerClient.get_last_octet_from_ip() takes 0 positional arguments but 1 was given
INFO:flwr:[flwr-clientapp] Push `ClientAppOutputs` for token 14306007644729170648
INFO:test:[2025-05-26 03:11:32.141136] Stopping power monitor via atexit...
INFO:test:Measured power consumption: Duration=34.430653s, Data size=2925 samples.
INFO:test:['[2025-05-26 03:11:32.151119] Communication end: 1748229092.1511173']
INFO:test:['[2025-05-26 03:11:32.151680] Evaluation phase (eth0): [sent: 1159083, recv: 145231513]']
