INFO:test:['[2025-05-26 03:27:07.514923] Client Start!']
INFO:test:Using network interface: eth0
INFO:test:[2025-05-26 03:27:07.515644] Starting power monitoring...
INFO:test:[2025-05-26 03:27:17.872260] Client sampled for evaluate()
INFO:test:[2025-05-26 03:27:17.917845] Starting evaluation...
ERROR:flwr:ClientApp raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/clientapp/app.py", line 136, in run_clientapp
    reply_message = client_app(message=message, context=context)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/message_handler/message_handler.py", line 135, in handle_legacy_message_from_msgtype
    evaluate_res = maybe_call_evaluate(
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client.py", line 244, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/numpy_client.py", line 251, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/root/.flwr/apps/wwjang.e2fl.1.0.0.b270b87b/e2fl/client_app.py", line 220, in evaluate
    loss, accuracy = test(self.net, self.valloader, self.device)
  File "/root/.flwr/apps/wwjang.e2fl.1.0.0.b270b87b/e2fl/task.py", line 259, in test
    for batch in testloader:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 2766, in __getitems__
    batch = self.__getitem__(keys)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 2762, in __getitem__
    return self._getitem(key)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 2747, in _getitem
    formatted_output = format_table(
  File "/usr/local/lib/python3.10/dist-packages/datasets/formatting/formatting.py", line 639, in format_table
    return formatter(pa_table, query_type=query_type)
  File "/usr/local/lib/python3.10/dist-packages/datasets/formatting/formatting.py", line 407, in __call__
    return self.format_batch(pa_table)
  File "/usr/local/lib/python3.10/dist-packages/datasets/formatting/formatting.py", line 522, in format_batch
    return self.transform(batch)
  File "/root/.flwr/apps/wwjang.e2fl.1.0.0.b270b87b/e2fl/task.py", line 103, in apply_transforms
    batch["img"] = [transforms(img) for img in batch["img"]]
KeyError: 'img'
INFO:flwr:[flwr-clientapp] Push `ClientAppOutputs` for token 18150207342213733028
INFO:test:[2025-05-26 03:27:18.632880] Stopping power monitor via atexit...
INFO:test:Measured power consumption: Duration=11.127574s, Data size=950 samples.
INFO:test:['[2025-05-26 03:27:18.646111] Communication end: 1748230038.646109']
INFO:test:['[2025-05-26 03:27:18.646604] Evaluation phase (eth0): [sent: 21733, recv: 69479]']
