INFO:test:['[2025-05-26 03:17:13.160247] Client Start!']
INFO:test:Using network interface: eth0
INFO:test:[2025-05-26 03:17:13.160945] Starting power monitoring...
INFO:test:[2025-05-26 03:17:50.720992] Client sampled for fit()
INFO:test:Network usage during fit: [sent: 0, recv: 0]
INFO:test:[2025-05-26 03:17:50.813387] Starting training...
ERROR:flwr:ClientApp raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/clientapp/app.py", line 136, in run_clientapp
    reply_message = client_app(message=message, context=context)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/root/.flwr/apps/wwjang.e2fl.1.0.0.2be7fb1e/e2fl/client_app.py", line 159, in fit
    train_loss = train(
  File "/root/.flwr/apps/wwjang.e2fl.1.0.0.2be7fb1e/e2fl/task.py", line 244, in train
    loss = criterion(net(images.to(device)), labels.to(device))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/models/alexnet.py", line 48, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/pooling.py", line 164, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "/usr/local/lib/python3.10/dist-packages/torch/_jit_internal.py", line 499, in fn
    return if_false(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 796, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (256x1x1). Calculated output size: (256x0x0). Output size is too small
INFO:flwr:[flwr-clientapp] Push `ClientAppOutputs` for token 6201868704937037862
INFO:test:[2025-05-26 03:17:51.546391] Stopping power monitor via atexit...
INFO:test:Measured power consumption: Duration=38.391481s, Data size=3262 samples.
INFO:test:['[2025-05-26 03:17:51.560419] Communication end: 1748229471.5604181']
INFO:test:['[2025-05-26 03:17:51.561084] Evaluation phase (eth0): [sent: 1176380, recv: 145343706]']
