INFO:test:['[2025-05-14 03:10:55.435593] Client Start!']
INFO:test:Using network interface: eth0
INFO:test:[2025-05-14 03:10:55.436313] Starting power monitoring...
ERROR:flwr:ClientApp raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/clientapp/app.py", line 136, in run_clientapp
    reply_message = client_app(message=message, context=context)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/usr/local/lib/python3.10/dist-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/root/.flwr/apps/wwjang.e2fl.1.0.0.9ca534de/e2fl/client_app.py", line 284, in client_fn
    model_name = context.node_config["model"]
KeyError: 'model'
INFO:flwr:[flwr-clientapp] Push `ClientAppOutputs` for token 15796182173253030981
INFO:test:[2025-05-14 03:10:56.615550] Stopping power monitor via atexit...
INFO:test:Measured power consumption: Duration=1.184831s, Data size=102 samples.
INFO:test:['[2025-05-14 03:10:56.622213] Communication end: 1747192256.622212']
INFO:test:['[2025-05-14 03:10:56.622777] Evaluation phase (eth0): [sent: 311, recv: 232]']
